### ISSUE TITLE
[Feature] Document server hardware requirements for number of users

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamuluswebsite#54]
Many people (including myself) have almost no idea how many users a specific server might be able to handle (e.g. with -T, without -T etc.) https://jamulus.io/wiki/Network-Requirements links network requirements.

It's not easy to say how many users a specific machine might support, but we could give some hints. 

An easy to understand table/description how much power a server needs for 
5
10
20
30
50
100

clients.

**Comment by gilgongo** [comment]
This also implicates [this page](https://jamulus.io/wiki/Network-Requirements), since bandwidth is a consideration as well. 

BTW while I appreciate your use of a templated _structure_ for issues, literally echoing the template headings _and_ guidance notes does makes it rather hard to read :-) I've taken the liberty of editing it to demonstrate what I mean, hope that's OK.

**Comment by ann0see** [comment]
> This also implicates this page, since bandwidth is a consideration as well.

Yes

Concerning the structure: yes. I will note that. We will have to change the templates then.

**Comment by gilgongo** [comment]
No need to change the templates.  I've got no problem with the structure itself, just the noise if the template and content are combined in the ticket.

**Comment by vdellamea** [comment]
Since it is difficult to write a rule, what if the server requirements documentation starts with a known list of functioning configurations? Another thread is running now on Facebook with a lot of useful information, but yet is difficult to summarize.

**Comment by gilgongo** [comment]
From what I can tell, the issue of server "sizing" (in any field, not just Jamulus) largely boils down to starting with some general "ball park" parameters, then refining it for your own circumstances. So we could provide general "guidelines" perhaps based on ensemble size and likely modifications (eg if you are wanting to pipe things to Zoom or whatnot)? [This page](https://jamulus.io/wiki/Network-Requirements) has also proved useful for bandwidth illustration too.

**Comment by gene96817** [comment]
With the table of bandwidth requirements, it seems we can translate it into server sizing estimates. Can't we have a model that focuses on three main parts: (1) processing of N audio streams, (2) managing the networking for N destinations, and (3) Jamulus overhead and any nonlinearities of the overhead. It would be good to start with a simple linear model for (1) and (2). Then we can refine it with the non-linear processing load (aka N^2 or N log N growth, etc.) Hopefully, the other overhead elements of (3) are not significant. 

What would be considered for "refining it for your own circumstances"? Link latency?

**Comment by gilgongo** [comment]
> What would be considered for "refining it for your own circumstances"?

I was thinking about things like taking audio streams out to Zoom or some such "extra" stuff (I think Worldjam uses a separate machine for that, for example). 

But that's really stuff we can't help out with other than giving example configs that other people have. Ultimately, if your server's in the cloud, you can just add/subtract resources as you need once you are in the right "ballpark" I think. The role of any help page is really to point you in the right direction. Eg if you are planning on just having, say, 6 people play every week on your server, then network latency and client issues are all you really need to worry about, since any modern server config will be fine.

**Comment by ann0see** [comment]
See https://github.com/jamulussoftware/jamuluswebsite/discussions/335

**Comment by gilgongo** [comment]
This is now duplicating https://github.com/jamulussoftware/jamuluswebsite/discussions/335 so I'll close this issue and we can then raise an agreed spec for the work (or someone can do it once agreed on the discussion and raise a PR).

**Comment by ve3meo** [comment]
The link https://github.com/jamulussoftware/jamuluswebsite/discussions/335 gives a 404

**Comment by ann0see** [comment]
Yes. You're right. I couldn't find the real discussion either.

**Comment by ann0see** [comment]
@ve3meo https://github.com/jamulussoftware/jamulus/discussions/1133 might be the correct one

**Comment by ve3meo** [comment]
> @ve3meo [jamulussoftware/jamulus#1133](https://github.com/jamulussoftware/jamulus/discussions/1133) might be the correct one

@ann0see That discussion links back to this one so I'm getting dizzy...

**Comment by gilgongo** [comment]
> The link https://github.com/jamulussoftware/jamuluswebsite/discussions/335 gives a 404

Sorry, it was removed when we shut down the separate website discussions area. It was a duplicate so we didn't move it across.  

https://github.com/jamulussoftware/jamulus/discussions/1133 is where it's at. I'll lock this now for that reason.
