### ISSUE TITLE
Good practice for acronym : use a abbr tag with title

### ISSUE THREAD

**Issue by gegeweb** [jamulussoftware/jamuluswebsite#91]
As mentioned in #90 and used in `fr-Central-Server.md`for the french translation of GUI, a good/best practice for acronyms  is to enclose these inside a `<abbr>`tag with a title, like this:

```html
<abbr title="JACK Audio Connection Kit">JACK</abbr>
```

Or this in `fr-Central-Server.md`:
```md
Serveurs sans <abbr title="Interface utilisateur graphique">IUG</abbr>
```

That show a help pointer when the mouse is hover and the content of the tootltip wich explain the signification of the acronym.

There is a lot of acronyms in the Jamulus's documentation, so it should be generalized and applied on each acronym.

I have already applied this practice on some pages in French translation for WAN, NAT, IUG...

**Comment by trebmuh** [comment]
Agreed that this is a good idea "in general".

That said, we must think from a reader perspective too. At a first idea, I'd only use that the first time an acronym is appearing on a page. After that, we can consider that the reader is aware of the meaning of the acronym. Why doing so? So as not to clutter up reading with too many distracting things.


> I have already applied this practice on some pages in French translation for WAN, NAT, IUG...

Once again, we shouldn't doing so unless a very good reason. "IUG" is one of those good reason since "GUI" is relatively well known in English (still I've some doubt about that if we consider people over 45/50 yo as an example), but IUG isn't very well known since the usual translation for "GUI" is "interface graphique" in French. You have choosen to keep an acronyme so this is a good reason for adding the abbr HTML code. For WAN/NAT/... there is AFAIK no reason to use the abbr in the French translation if it isn't present in the English text first.

**Comment by gegeweb** [comment]
> For WAN/NAT/... there is AFAIK no reason to use the abbr in the French translation if it isn't present in the English text first.

OK, I had remove these. If there's any left, it's because I missed it. I'll recheck before reviews…

**Comment by trebmuh** [comment]
(_reminder: https://github.com/jamulussoftware/jamuluswebsite/pull/111#pullrequestreview-548871589_)

**Comment by ann0see** [comment]
@gegeweb @trebmuh could one of you open a pr against changes with the <abbr> tag to the english translation? At least for some sites

**Comment by ann0see** [comment]
Closing since it's not an issue. More of a guideline for the contribution pages.
